### ISSUE TITLE
How Can I save the plot?

### ISSUE THREAD

**Issue by shenwei356** [lmrodriguezr/nonpareil#11]
Hi, 

How can I save the Nonpareil curves to files? I run it in ssh client, without X windows.

Thanks

**Comment by lmrodriguezr** [comment]
This code should do the trick:

    pdf('Nonpareil-plot.pdf')
    Nonpareil.curve(...) # Or Nonpareil.curve.batch(...)
    dev.off()

**Comment by shenwei356** [comment]
Thank you @lmrodriguezr
