### ISSUE TITLE
Fatal error: Cannot open the file: reads.fa

### ISSUE THREAD

**Issue by shimingt** [lmrodriguezr/nonpareil#19]
Hello there,

I have an error when I tried to run nonpareil:

tanshiming@S620100019205:~/Documents/nonpareil-trial$ nonpareil -s reads.fa -b output
Nonpareil v3
 [      0.0]  Counting sequences
Fatal error:
Cannot open the file: 
reads.fa
 [      0.0] Fatal error: Cannot open the file: reads.fa

I have tried doing this on fasta and fastq files; the files are an illumina-trimmed dataset. Can someone please advice?

Thanks!

**Comment by gisleDK** [comment]
It sounds like the file, reads.fa, is not found. Try specifying exact path of reads.fa

**Comment by gunturus** [comment]
how did install nonpareil. Did you use the release or did you clone

**Comment by shimingt** [comment]
Hello @gunturus , I git cloned nonpareil. I did exactly everything that was mentioned on Nonpareil webpage, but I still got the error message.

**Comment by lmrodriguezr** [comment]
Is the file `reads.fa` present in `~/Documents/nonpareil-trial`? Please do `ls ~/Documents/nonpareil-trial` and post the output.

**Comment by shimingt** [comment]
Hello Guys,

Sorry for the late reply. Here is the output:

tanshiming@S620100019205:~/Documents/nonpareil-trial$ ls ~/Documents/nonpareil-trial
reads.fasta  UPWRP0508161KA_TCCGGAGA-ATAGAGGC_L1L2_R1_001.fastq

My reads.fasta file is definitely in the same folder. 

Any suggestions?

**Comment by gisleDK** [comment]
reads.fa ≠ reads.fasta
