### ISSUE TITLE
make nonpareil-mpi failed: enveomics/SeqReader.o: No such file or directory

### ISSUE THREAD

**Issue by wwood** [lmrodriguezr/nonpareil#21]
Hi,

Came across this running `make nonpareil-mpi`:
```
cd enveomics/ && make nonpareil-mpi
make[1]: Entering directory '/tmp/guix-build-nonpareil-2.4.1-1.72ce3c9e.drv-0/source/enveomics'
mpic++ -DENVEOMICS_MULTI_NODE universal.cpp -c -Wall -std=c++11
mpic++ -DENVEOMICS_MULTI_NODE multinode.cpp -c -Wall -std=c++11
mpic++ -DENVEOMICS_MULTI_NODE sequence.cpp -c -Wall -std=c++11
mpic++ -DENVEOMICS_MULTI_NODE nonpareil_mating.cpp -c -Wall -std=c++11
mpic++ -DENVEOMICS_MULTI_NODE nonpareil_sampling.cpp -c -Wall -std=c++11
make[1]: Leaving directory '/tmp/guix-build-nonpareil-2.4.1-1.72ce3c9e.drv-0/source/enveomics'
mpic++ nonpareil.cpp enveomics/universal.o enveomics/multinode.o enveomics/sequence.o enveomics/SeqReader.o  enveomics/KmerCounter.o enveomics/References.o enveomics/Hash.o enveomics/nonpareil_mating.o enveomics/nonpareil_sampling.o -lpthread -DENVEOMICS_MULTI_NODE -Wall -std=c++11 -o nonpareil-mpi
g++: error: enveomics/SeqReader.o: No such file or directory
g++: error: enveomics/KmerCounter.o: No such file or directory
g++: error: enveomics/References.o: No such file or directory
g++: error: enveomics/Hash.o: No such file or directory
make: *** [Makefile:30: nonpareil-mpi] Error 1
```
I believe this is caused by not all the objects being compiled in `enveomics/Makefile`. I was able to workaround this using something similar to `make nonpareil; make nonpareil-mpi`.

Can I ask also, does it make sense to use the git or the release, since the newest release is from 2015?
ta
ben

**Comment by gunturus** [comment]
Hi ben,

We have made some important changes to nonpareil.

I would re clone and compile again as I made some changes to the options and help print just right now. To improve the speed of nonpareil, we developed a kmer based algorithm which is many times faster than aligning the reads. You will be able to process soil metagenomes on a single desktop within two hours depending on the size of the metagenome. The kmer and alignment algorithm will gave you essentially the same result. You will be required to use the -T option to choose the algorithm.

I wouldn't use the newest release.

Santosh
