### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Freemacl** [lmrodriguezr/nonpareil#30]
Hello,

I saw there were a couple of closed issues reporting something similar, but it seems like they were all corrected by updating. I am using Nonpareil v3.2, just installed today via conda.

I executed this command:
nonpareil -s ~/pathto/seqs.fastq -T kmer -f fastq -t 2

Which produced this output:
Nonpareil v3.2
 [      0.0]  reading /home/imss/Vault/Community/NunavutWWTPMetagen/Reads/18SEPin4_R1.fastq
 [      0.0]  Picking 10000 random sequences
 [      0.0]  Started counting
Segmentation fault (core dumped)

**Comment by gunturus** [comment]
can you output the first 10 lines of the fastq file. You are missing -b option on your command.
-b refers to the prefix of the output files

**Comment by Freemacl** [comment]
Wow easy fix... Thank you for the quick response!

**Comment by gunturus** [comment]
I will make -b a requirement and give a proper message.

thank you for noticing the problem.
