### ISSUE TITLE
The problem with xlim

### ISSUE THREAD

**Issue by IM-han** [lmrodriguezr/nonpareil#33]
When I plot a curve with the code "Nonpareil.curve.batch(File,libnames=Name,xlim = c(1e+8,1e+15))",but the xlim didnot work.　The picture is below. I want to get the x-axis bigger, so that it can show more information. The parameter xlim only work in Nonpareil.curve(), and it dosenot work in Nonpareil.curve.batch(). And I want to know what mean is the "arrow" in a picture.
![default](https://user-images.githubusercontent.com/33390378/37949299-9b4c4cf8-31c6-11e8-9d3c-0c33e7a80b37.png)

**Comment by gunturus** [comment]
The arrow points to the inflection point of the curve.

**Comment by lmrodriguezr** [comment]
Hello @IM-han 

Try passing `xlim` explicitly as a plot option:
```R
Nonpareil.curve.batch(File, libnames=Name, plot.opts=list(xlim=c(1e+8,1e+15)))
```

**Comment by IM-han** [comment]
Thank you. I get it. How about the picture below. Dose the circle on the curve mean the same with the arrow in the picture I get ? 
![default](https://user-images.githubusercontent.com/33390378/38003064-59ac1538-3268-11e8-8596-b3919e2d2934.png)

**Comment by lmrodriguezr** [comment]
No, the circle means the actual sequencing effort and estimated average coverage of the sample. It's the equivalent to the rightmost end of the solid lines in the previous figure.

You can check out this example:
http://enve-omics.ce.gatech.edu/nonpareil/results?jid=example1

Play with the radio selects (Plot model only, Plot curve only, and Plot curve and model) to see how they correspond to each other.

It's strange that this last figure doesn't include the arrows, perhaps you turned off the arrow plotting with `plot.diversity=FALSE`? Or maybe they happen to be hidden behind the legend box?

I'm closing this issue, but please feel free to comment again and/or reopen if you have any more questions.
