### ISSUE TITLE
Unable to find required package ‘Nonpareil’ in the R package

### ISSUE THREAD

**Issue by shimingt** [lmrodriguezr/nonpareil#36]
Dear Luis,

I have installed nonpareil using conda, and have successfully performed obtain the .npo files. Unfortunately, I am not able to load the nonpareil package library in R. 

```
> library(Nonpareil)
Error in library(Nonpareil) : there is no package called ‘Nonpareil’
```
I have also tried to install nonpareil using the "make" command, but to no avail.

Will appreciate any help that can be rendered.

Thank you!

**Comment by lmrodriguezr** [comment]
Hello @shimingt 

The Nonpareil package is available in the official CRAN repository, so you can simply run this in R:

```R
install.packages('Nonpareil')
```

I'll close the issue for now, but please feel free to respond if you want us to reopen.

Best,
Miguel.
