### ISSUE TITLE
extracting out "final coverage" , "actual effort" and "required effort" in numbers from .npo file

### ISSUE THREAD

**Issue by Jigyasa3** [lmrodriguezr/nonpareil#40]
Hey @lmrodriguezr  @bebatut @gunturus 

I was wondering if it's possible to extract out the actual values of stats measured by nonpareil software directly, without the R graph. 

I am looking at 200 samples and visualizing all of them on a plot doesn't work. So, I wanted  to get the values of "final coverage" , "actual sequencing effort" and "required sequencing effort" in numbers from .npo file to compare among samples?

Thanks!

**Comment by lmrodriguezr** [comment]
To turn off plotting simply pass `plot = FALSE`.

You can call the typical summary functions on the output (`summary` or `print`) to show all the statistics from a single curve or a curve set. See the examples in `?Nonpareil.set` and `?Nonpareil.curve`. The `.npo` files only have redundancy information, not coverage, so you cannot extract those values directly. You still need the R package, but you don't need the graph for that.
