### ISSUE TITLE
number of initial reads

### ISSUE THREAD

**Issue by lalalagartija** [lmrodriguezr/nonpareil#49]
This is more of a question than an issue but : 
is nonpareil biases on the number of initial reads we give it ? Should we change -X to more if we have datasets with great number of reads ?

And also, just to be sure : this tool works with shotgun not amplicon metagenomes right ? 

Thank you very much in advance,

**Comment by lmrodriguezr** [comment]
Hello,

In theory, yes, you could get more robust estimates by increasing `-X`. However, in our tests, this is only the case when we get into the Tbp sizes. If that's your case, I would suggest increasing `-X` (e.g., 10-fold for 1Tb), and using the _k_-mer kernel (or the multi-node mode, if you prefer the alignment kernel).

Yes, this tool is designed for WGS metagenomes (not amplicons).

I'll close this issue, but please feel free to reopen if you have any other related questions (or open new ones).

Best wishes
Miguel.
