### ISSUE TITLE
Re-add factor to curve?

### ISSUE THREAD

**Issue by sjaenick** [lmrodriguezr/nonpareil#52]
Hi,

earlier releases of the package (I checked v2.3) supported a 'factor' argument for the curve that allowed
to easily switch from bp to Mbp/Gbp/.. - but also mentioned that this could possibly influence the fit of the
model. Would it be possible to re-introduce something similar again, maybe not for the curve but only as
an additional argument to the plot function (so model fit wouldn't change)?

**Comment by lmrodriguezr** [comment]
Hello,

That's a very good suggestion! You can currently do it with:
```R
Nonpareil.curve(file, xaxt = "n")
axis(1, at = 10^c(3, 6, 9 , 12), labels = paste(1, c("Kbp", "Mbp", "Gbp", "Tbp")))
```

I'll add that to the documentation momentarily so it's easily accessible.

Thanks!
Miguel.
