### ISSUE TITLE
Fatal error: Reduce the number of query reads (-X)

### ISSUE THREAD

**Issue by dtsementzi3** [lmrodriguezr/nonpareil#53]
I had the following fatal error while running nonpareil Nonpareil v3.4 as follows:

nonpareil -T kmer -s ../xx.human/$DS.NonHuman.1.fa -b np$DS -t 16 -f fasta -X 100

Fatal error:
Reduce the number of query reads (-X) to 10%% of total reads
 [      0.0] Fatal error: Reduce the number of query reads (-X) to 10%% of total reads

It turns out I had an error in the path (my files names are *.fasta and not *.fa), so when that was fixed it runs fine. But the error message is misleading

Thank you!

**Comment by lmrodriguezr** [comment]
Thanks! misleading indeed. I'm fixing this soon

**Comment by Junhao-Guo** [comment]
hello, I had the same problem.How can I fix it ?
