### ISSUE TITLE
Default output prefix not very friendly

### ISSUE THREAD

**Issue by jfy133** [lmrodriguezr/nonpareil#67]
Running

```
./nonpareil-3.5.2-Linux_x86_64 -s ERX5474932_ERR5766176_2.fastq.gz -T kmer -f fastq 
```

produces 

```
-rw-rw-r-- 1 james james 833K Jun 28 12:39 ''$'\205\300\017\205\277''.npa'
-rw-rw-r-- 1 james james  20K Jun 28 12:39 ''$'\205\300\017\205\277''.npc'
-rw-rw-r-- 1 james james 1.9K Jun 28 12:39 ''$'\205\300\017\205\277''.npl'
-rw-rw-r-- 1 james james 1.8K Jun 28 12:39 ''$'\205\300\017\205\277''.npo'
```

Which is not a very Unix friendly default. I would recommend making teh default `-b` to be either e.g. `nonpareil.npa` or maybe take the file name input without the suffix fasta/fastq/fasta.gz/fastq.gz suffix

(note specifying `-b` works as expected) :)

**Comment by lmrodriguezr** [comment]
That's a very good suggestion! I always pass `-b`, but having a friendly default is much better

**Comment by jfy133** [comment]
Either that or make `-b` required :)(

**Comment by jfy133** [comment]
Works nicely, hanks :D
