### ISSUE TITLE
Failure to generate nonpareil curves

### ISSUE THREAD

**Issue by carden24** [lmrodriguezr/nonpareil#9]
I have problems making the nonpareil curves with R. 
I run mpi nonpareil as usual except I use the -L 25 options because I expect poor coverage. I also know from pyrotag data that I have closely related species in my samples. 
There was no errors in running nonpareil and I get "everything seems correct result'
However when I try to get the curves I get the following warning messages:

Warning messages:
...Convergence failure: false convergence (8)
...Model didn't converge

My questions are:
-Is my coverage result still valid?
-Do I need to rerun nonpareil with different paramaters? or the modelling of the curves only affects the sequencing effort needed. 

thanks, 
Erick

**Comment by lmrodriguezr** [comment]
Solved in v2.400
